api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path('', views.index, name='index'),
    path('version/', views.version, name='version'),
    path('status/', views.status, name='status'),
    path('login/', views.login, name='login'),
    ]

main/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls', namespace='homepage')),
    path('docs/', include('docs.urls', namespace='docs')),
    path('api/', include('api.urls', namespace='api')),
    path('admin/', admin.site.urls),
]

common/templates/common/base.html
{% load static %}
{% load compress %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>pycheck</title>

    <link rel="stylesheet" type="text/css" href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'node_modules/bootstrap-icons/font/bootstrap-icons.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'node_modules/@highlightjs/cdn-assets/styles/default.min.css' %}">

    {% compress css %}
    <link rel="stylesheet" type="text/x-scss" href="{% static 'common/css/main.scss' %}">
    {% block css %}{% endblock css %}
    {% endcompress %}
  </head>
  <body>
    <header class="sticky-top">
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
          <a class="navbar-brand" href="/"><h2><i class="bi bi-check-circle"></i> pycheck</h2></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle active" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Docs
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'docs:index' %}#instalacion">Instalación</a></li>
                  <li><a class="dropdown-item" href="{% url 'docs:index' %}#version">Versión</a></li>
                  <li><a class="dropdown-item" href="{% url 'docs:index' %}#actualizacion">Actualización</a></li>
                  <li><a class="dropdown-item" href="{% url 'docs:index' %}#docs">Documentación</a></li>
                  <li><a class="dropdown-item" href="{% url 'docs:index' %}#enunciado">Enunciado</a></li>
                  <li><a class="dropdown-item" href="{% url 'docs:index' %}#plantilla">Plantilla</a></li>
                  <li><a class="dropdown-item" href="{% url 'docs:index' %}#arranque">Arranque</a></li>
                  <li><a class="dropdown-item" href="{% url 'docs:index' %}#comprobacion">Comprobación</a></li>
                  <li><a class="dropdown-item" href="{% url 'docs:index' %}#ejecucion">Ejecución</a></li>
                </ul>
              </li>
              {% comment %} <li class="nav-item">
                <a class="nav-link" aria-current="page" href="#">Home</a>
              </li> {% endcomment %}
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="container content">
      {% block content %}{% endblock content %}
    </div>

    <footer class="bg-warning text-center">
      <div class="container">
        <span class="text-muted">Hecho con <i class="bi bi-heart"></i> por Sergio Delgado Quintero</span>
      </div>
    </footer>

    <!-- Back to top button -->
    <button type="button" class="btn btn-danger btn-floating btn-lg" id="btn-back-to-top">
      <i class="bi bi-arrow-up"></i>
    </button>
    
    <script src="{% static 'node_modules/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'node_modules/@highlightjs/cdn-assets/highlight.min.js' %}"></script>
    <script src="{% static 'node_modules/highlightjs-line-numbers.js/dist/highlightjs-line-numbers.min.js' %}"></script>
    
    {% compress js %}
    <script src="{% static 'common/js/utils.js' %}"></script>
    <script src="{% static 'common/js/main.js' %}"></script>
    {% block js %}{% endblock js %}
    {% endcompress %}
  </body>
</html>